apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: color-app-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/mjankula/root-app.git' # <-- Change to your repo URL
        revision: main
        files:
          - path: "my-webapp/environments/config.json"

  # The template for the Argo CD Application remains the same.
  template:
    metadata:
      name: 'color-app-change2-{{namespace}}' # {{name}} will now be 'blue'
      namespace: openshift-gitops
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}' # Deploys to the 'blue' namespace

      source:
        repoURL: 'https://github.com/mjankula/root-app.git' 
        targetRevision: main
        path: my-webapp/helm-chart
        helm:
          parameters:
            - name: 'color'
              value: '{{color}}' # Passes 'blue' as the Helm value
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
